import type { Mission } from "./types";

export const missions: Mission[] = [
  { id: "classroom-supplies", number: 1, title: "가까운 교실 준비물", cargo: "가벼운 종이·필기도구 상자", purpose: "교실 준비물 놓는 곳으로 옮겨요.", load: "light", distance: "near", path: "flat", energy: ["사람의 힘 사용 가능", "충전 필요 없음"], energyAvailability: ["human-power-ok"], control: "평평하고 좁은 실내 길에서 방향을 바꿔요.", minimumStability: 1, minimumControl: 2, notes: ["가벼운 구조", "쉬운 회전"] },
  { id: "library-books", number: 2, title: "도서관 책 상자", cargo: "무거운 책 상자", purpose: "도서관 정리 공간으로 옮겨요.", load: "heavy", distance: "medium", path: "flat", energy: ["충전 장소 이용 가능"], energyAvailability: ["charging-available"], control: "넓고 평평한 길에서 멈출 수 있어야 해요.", minimumStability: 1, minimumControl: 1, notes: ["하중을 받치는 구조", "배터리·재료 부담"] },
  { id: "garden-seedlings", number: 3, title: "학교 텃밭 묘목 옮기기", cargo: "쉽게 넘어질 수 있는 보통 무게 묘목 상자", purpose: "텃밭으로 조심히 옮겨요.", load: "medium", distance: "medium", path: "rough", energy: ["사람의 힘 또는 조금만 충전"], energyAvailability: ["human-power-ok", "limited-charging"], control: "울퉁불퉁한 길에서 안정적으로 움직여요.", minimumStability: 2, minimumControl: 2, notes: ["낮은 무게 중심", "울퉁불퉁한 길에서 덜 미끄러지기"] },
  { id: "hill-observation", number: 4, title: "언덕 위 과학 상자", cargo: "보통 무게의 과학 상자", purpose: "언덕 위 과학 활동 장소로 옮겨요.", load: "medium", distance: "far", path: "uphill", energy: ["출발할 때 충전 가능", "가는 길에는 충전할 곳 없음"], energyAvailability: ["charging-available"], control: "경사에서 방향을 바꾸고 멈춰요.", minimumStability: 2, minimumControl: 2, notes: ["먼 거리와 경사", "충전할 곳"] },
  { id: "changed-conditions", number: 5, title: "날씨가 바뀐 날 다시 만들기", cargo: "흐린 날 더 무거워진 상자", purpose: "울퉁불퉁한 돌아가는 길로 옮겨요.", load: "medium", distance: "medium", path: "rough", energy: ["흐린 날", "조금만 충전 가능"], energyAvailability: ["limited-charging", "cloudy"], control: "돌아가는 길에서 안정적으로 멈춰요.", minimumStability: 2, minimumControl: 2, notes: ["날씨와 길이 바뀜", "한 부품만 먼저 바꾸기"], conditionChange: { before: ["밝은 낮", "중간 거리", "평평한 길", "가벼운 짐"], after: ["흐린 날", "울퉁불퉁한 길", "보통 무게 짐", "조금만 충전 가능"], initialRequirements: { cargo: "밝은 낮의 가벼운 상자", load: "light", distance: "medium", path: "flat", energy: ["밝은 낮", "햇빛 충전 보조 가능"], energyAvailability: ["human-power-ok", "daylight-supplement"], control: "평평한 길에서 방향을 바꾸고 멈춰요.", minimumStability: 1, minimumControl: 1 } } },
];

export const getFirstDesignMission = (mission: Mission): Mission => mission.conditionChange ? { ...mission, ...mission.conditionChange.initialRequirements } : mission;
