"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { components, byId } from "./transport/components";
import { HelpDialog } from "./transport/Dialogs";
import { compareEvaluations, evaluateDesign, getRedesignChoices, isSingleComponentChange } from "./transport/evaluator";
import { getFirstDesignMission, missions } from "./transport/missions";
import { PrototypePreview } from "./transport/PrototypePreview";
import { groupLabels, type ComponentGroup, type ConditionId, type Evaluation, type TransportDesign } from "./transport/types";

type Phase = "welcome" | "tutorial" | "missions" | "brief" | "conditions" | "build" | "first-test" | "goal" | "redesign" | "second-test" | "compare" | "report";
const groups = Object.keys(groupLabels) as ComponentGroup[];
const statusText = { fits: "✓ 잘 맞아요", partial: "◐ 일부는 맞지만 살펴볼 점이 있어요", redesign: "↻ 다시 설계해 봐요" };
const conditionCards = (mission: (typeof missions)[number]) => [
  ["짐", mission.cargo], ["거리", mission.distance === "near" ? "가까운 거리" : mission.distance === "medium" ? "중간 거리" : "먼 거리"], ["길", mission.path === "flat" ? "평평한 길" : mission.path === "rough" ? "울퉁불퉁한 길" : "완만한 오르막"], ["에너지", mission.energy.join(" · ")], ["조향·제동", mission.control],
];
const emptySelection = (): Partial<Record<ComponentGroup, string>> => ({});

function ResultBoard({ evaluation }: { evaluation: Evaluation }) {
  return <><section className="result-board" aria-label="조건별 시험 결과" aria-live="polite"><h2>조건별 시험 결과</h2>{evaluation.conditionResults.map((result) => <article className={`result ${result.status}`} key={result.conditionId}><h3>{statusText[result.status]} · {result.label}</h3><p>{result.explanation}</p><p className="muted">함께 생각할 점: {result.tradeoffNotes[0]}</p></article>)}</section><section className="environment"><h2>에너지·환경 프로필</h2><div><b>운행 중</b><p>{evaluation.environmentalProfile.usePhaseEnergy}</p></div><div><b>에너지 마련</b><p>{evaluation.environmentalProfile.chargingOrWeatherCondition}</p></div><div><b>재료·배터리</b><p>{evaluation.environmentalProfile.materialAndBatteryNote}</p></div></section></>;
}

export default function TransportApp() {
  const [phase, setPhase] = useState<Phase>("welcome"); const [missionId, setMissionId] = useState(missions[0].id);
  const [reviewed, setReviewed] = useState<string[]>([]); const [selection, setSelection] = useState(emptySelection);
  const [first, setFirst] = useState<TransportDesign | null>(null); const [second, setSecond] = useState<TransportDesign | null>(null);
  const [target, setTarget] = useState<ConditionId | "">(""); const [strength, setStrength] = useState<ConditionId | "">(""); const [changeGroup, setChangeGroup] = useState<ComponentGroup | "">("");
  const [dialog, setDialog] = useState<"updates" | "teacher" | "principles" | null>(null); const [reports, setReports] = useState<string[]>([]);
  const resultHeadingRef = useRef<HTMLHeadingElement>(null);
  const mission = missions.find((item) => item.id === missionId)!;
  const firstDesignMission = useMemo(() => getFirstDesignMission(mission), [mission]);
  const firstEvaluation = useMemo(() => first ? evaluateDesign(firstDesignMission, first, components) : null, [firstDesignMission, first]);
  const redesignBaseEvaluation = useMemo(() => first ? evaluateDesign(mission, first, components) : null, [mission, first]);
  const secondEvaluation = useMemo(() => second ? evaluateDesign(mission, second, components) : null, [mission, second]);
  const redesignChoices = redesignBaseEvaluation ? getRedesignChoices(redesignBaseEvaluation) : { targets: [], strengths: [] };
  const changedGroup = first && second ? groups.find((group) => first.componentIds[group] !== second.componentIds[group]) : undefined;
  const changedComponent = changedGroup && second ? byId(second.componentIds[changedGroup]) : undefined;
  const tradeoff = redesignBaseEvaluation && secondEvaluation && changedComponent ? compareEvaluations(redesignBaseEvaluation, secondEvaluation, changedComponent.burden) : null;
  useEffect(() => { if (phase === "first-test" || phase === "second-test") resultHeadingRef.current?.focus(); }, [phase]);
  const setPart = (group: ComponentGroup, id: string) => setSelection((old) => ({ ...old, [group]: id }));
  const createFirst = () => { const design = { id: "first", missionId, componentIds: selection as Record<ComponentGroup, string> }; setFirst(design); setPhase("first-test"); };
  const startRedesign = () => { setSelection(first?.componentIds ?? {}); setChangeGroup(""); setPhase("redesign"); };
  const createSecond = () => { const design = { id: "second", missionId, componentIds: selection as Record<ComponentGroup, string> }; if (first && isSingleComponentChange(first, design)) { setSecond(design); setPhase("second-test"); } };
  const progress = ["의뢰", "조건", "조립", "첫 시험", "재설계", "비교서"];
  const phaseIndex = phase === "welcome" || phase === "tutorial" || phase === "missions" || phase === "brief" ? 0 : phase === "conditions" ? 1 : phase === "build" ? 2 : phase === "first-test" ? 3 : phase === "goal" || phase === "redesign" || phase === "second-test" ? 4 : 5;
  return <main><header className="topbar"><a className="brand" href="#main">친환경 수송 <span>조건 설계소</span></a><div className="utility"><button onClick={() => setDialog("principles")}>설계 원칙</button><button onClick={() => setDialog("teacher")}>교사용 안내</button><button onClick={() => setDialog("updates")}>업데이트 내역</button></div></header>
    <div className="progress" aria-label={`현재 단계: ${progress[phaseIndex]}`}>{progress.map((item, index) => <span key={item} className={index === phaseIndex ? "current" : index < phaseIndex ? "done" : ""} aria-current={index === phaseIndex ? "step" : undefined}>{index + 1}. {item}</span>)}</div>
    <div id="main" className="app-shell">
      {phase === "welcome" ? <section className="welcome"><p className="leaf">수송은 사람이나 물건을 다른 곳으로 옮기는 일이에요.</p><h1>거리·짐·길·에너지 조건을 읽고<br />나만의 수송 시제품을 설계해요.</h1><p>가상 학교 안의 물품을 옮기는 교육용 생각 실험입니다. 가장 높은 점수를 찾는 활동이 아니에요.</p><div className="welcome-actions"><button className="primary" onClick={() => setPhase("tutorial")}>안내 실험 시작</button><button onClick={() => setPhase("missions")}>안내 건너뛰기</button></div><p className="safety">화면 속 결과는 실제 차량의 성능이나 안전을 보증하지 않아요.</p></section> : null}
      {phase === "tutorial" ? <section className="panel tutorial"><h1>같은 수레도 임무가 달라지면 달라져요</h1><div className="tutorial-grid"><article><b>설계 A</b><p>가벼운 적재함 · 큰 바퀴 · 사람의 힘 · 기본 제동</p><p>가까운 평평한 길의 가벼운 상자에 도움이 될 수 있어요.</p></article><article><b>설계 B</b><p>튼튼한 적재함 · 넓은 바퀴 · 전동 보조 · 이중 제동</p><p>거친 오르막의 무거운 상자에 도움이 될 수 있어요.</p></article></div><p>결과는 총점이 아니라 조건별로 확인하고, 전기·태양광도 충전·재료·날씨를 함께 봐요.</p><button className="primary" onClick={() => setPhase("missions")}>임무 고르기</button></section> : null}
      {phase === "missions" ? <section><h1>수송 의뢰를 고르세요</h1><p className="lead">먼저 무엇을 어디까지 어떤 길로 옮길지 확인해요.</p><div className="mission-grid">{missions.map((item) => <button key={item.id} className="mission-card" onClick={() => { setMissionId(item.id); setReviewed([]); setSelection(emptySelection()); setFirst(null); setSecond(null); setTarget(""); setStrength(""); setChangeGroup(""); setPhase("brief"); }}><span>임무 {item.number}</span><b>{item.title}</b><small>{item.cargo}</small></button>)}</div></section> : null}
      {phase === "brief" ? <section className="panel brief"><p className="leaf">임무 {mission.number}</p><h1>{mission.title}</h1><p>{mission.purpose}</p><p><b>옮길 것:</b> {mission.cargo}</p>{mission.conditionChange ? <div className="condition-change"><div><b>처음 조건</b><p>{mission.conditionChange.before.join(" · ")}</p></div><div><b>바뀐 조건</b><p>{mission.conditionChange.after.join(" · ")}</p></div><p>조건이 바뀌었으니 가장 큰 영향을 받은 부품 하나를 먼저 바꾸어 봐요.</p></div> : null}<button className="primary" onClick={() => setPhase("conditions")}>조건표 읽기</button><button onClick={() => setPhase("missions")}>다른 임무 고르기</button></section> : null}
      {phase === "conditions" ? <section><h1>{mission.conditionChange ? "먼저 처음 조건을 확인해요" : "조건표를 하나씩 확인해요"}</h1><p className="lead">모든 조건을 펼쳐야 부품 선반이 열립니다.</p><div className="conditions">{conditionCards(firstDesignMission).map(([title, detail]) => <button key={title} className={reviewed.includes(title) ? "condition checked" : "condition"} onClick={() => setReviewed((old) => old.includes(title) ? old : [...old, title])}><b>{reviewed.includes(title) ? "✓ " : ""}{title}</b><span>{detail}</span></button>)}</div><button className="primary" disabled={reviewed.length < 5} aria-describedby="review-help" onClick={() => setPhase("build")}>구성 요소 고르기</button>{reviewed.length < 5 ? <p id="review-help" className="hint">아직 {5 - reviewed.length}개 조건을 확인해야 해요.</p> : null}</section> : null}
      {phase === "build" || phase === "redesign" ? <section className="build-layout"><div className="build-copy"><h1>{phase === "build" ? "첫 시제품을 조합해요" : "한 부품만 바꾸어 재설계해요"}</h1><p className="lead">{phase === "build" ? "각 부품군에서 하나씩 선택하세요. 장점과 부담을 먼저 볼 수 있어요." : "바꿀 부품군 하나를 고른 다음, 그 안에서 새 부품을 고르세요."}</p>{phase === "redesign" ? <fieldset className="change-group"><legend>바꿀 부품군 하나</legend>{groups.map((group) => <label key={group}><input type="radio" name="change-group" checked={changeGroup === group} onChange={() => setChangeGroup(group)} />{groupLabels[group]}</label>)}</fieldset> : null}</div><PrototypePreview selected={selection} /><div className="shelf">{groups.map((group) => (phase === "redesign" && changeGroup !== group) ? null : <fieldset key={group}><legend>{groupLabels[group]} <small>{group === "structure" ? "짐을 담고 받쳐요" : group === "movement" ? "길 위에서 굴러가요" : group === "energy" ? "움직일 힘을 마련해요" : "방향을 바꾸고 멈춰요"}</small></legend><div className="option-stack">{components.filter((item) => item.group === group).map((item) => <label className={selection[group] === item.id ? "option selected" : "option"} key={item.id}><input type="radio" name={group} checked={selection[group] === item.id} onChange={() => setPart(group, item.id)} /><span><b>{item.name}</b><small>{item.short}</small><em>도움: {item.strength}</em><em>부담: {item.burden}</em></span></label>)}</div></fieldset>)}</div><div className="actions">{phase === "build" ? <><button className="primary" disabled={groups.some((group) => !selection[group])} onClick={createFirst}>첫 설계 시험하기</button>{groups.some((group) => !selection[group]) ? <span className="hint">네 부품군을 모두 골라야 시험할 수 있어요.</span> : null}</> : <><button className="primary" disabled={!changeGroup || !first || !isSingleComponentChange(first, { id: "second", missionId, componentIds: selection as Record<ComponentGroup, string> })} onClick={createSecond}>바꾼 설계 시험하기</button><span className="hint">첫 설계와 정확히 한 부품군만 달라야 해요.</span></>}</div></section> : null}
      {phase === "first-test" && firstEvaluation ? <section><h1 ref={resultHeadingRef} tabIndex={-1}>첫 설계를 조건별로 살펴봐요</h1><ResultBoard evaluation={firstEvaluation} /><button className="primary" onClick={() => setPhase("goal")}>{mission.conditionChange ? "바뀐 조건 확인하기" : "재설계 목표 고르기"}</button></section> : null}
      {phase === "goal" && redesignBaseEvaluation ? <section className="goal"><h1>{mission.conditionChange ? "조건이 바뀌었어요" : "무엇을 개선하고, 무엇을 지킬까요?"}</h1>{mission.conditionChange ? <><div className="condition-change"><div><b>바뀐 조건</b><p>{mission.conditionChange.after.join(" · ")}</p></div><p>첫 설계를 바뀐 조건에 다시 대입한 결과를 보고, 부품 하나만 바꿔요.</p></div><ResultBoard evaluation={redesignBaseEvaluation} /></> : null}<p className="lead">실제 시험 결과에서 개선할 조건과 지킬 장점만 골라요.</p><fieldset><legend>개선할 조건 하나</legend>{redesignChoices.targets.map((item) => <label key={item.conditionId}><input type="radio" name="target" value={item.conditionId} checked={target === item.conditionId} onChange={() => { setTarget(item.conditionId); if (strength === item.conditionId) setStrength(""); }} />{item.label} · {statusText[item.status]}</label>)}</fieldset><fieldset><legend>그대로 지킬 장점 하나</legend>{redesignChoices.strengths.filter((item) => item.conditionId !== target).map((item) => <label key={item.conditionId}><input type="radio" name="strength" value={item.conditionId} checked={strength === item.conditionId} onChange={() => setStrength(item.conditionId)} />{item.label}의 근거를 지킬게요</label>)}</fieldset><button className="primary" disabled={!target || !strength || target === strength} onClick={startRedesign}>한 부품 바꾸기</button></section> : null}
      {phase === "second-test" && secondEvaluation ? <section><h1 ref={resultHeadingRef} tabIndex={-1}>바꾼 설계를 같은 조건에서 시험해요</h1><ResultBoard evaluation={secondEvaluation} /><button className="primary" onClick={() => setPhase("compare")}>두 설계 비교하기</button></section> : null}
      {phase === "compare" && first && second && redesignBaseEvaluation && secondEvaluation && changedGroup && changedComponent && tradeoff ? <section><h1>좋아진 점과 새 부담을 비교해요</h1><p className="lead">바꾼 부품: <b>{groupLabels[changedGroup]}</b> · {changedComponent.name}</p><div className="comparison">{[redesignBaseEvaluation, secondEvaluation].map((evaluation, index) => <article key={evaluation.designId}><h2>{index === 0 ? mission.conditionChange ? "바뀐 조건의 첫 설계" : "첫 설계" : "재설계"}</h2>{evaluation.conditionResults.map((result) => <p key={result.conditionId}><b>{result.label}</b><br />{statusText[result.status]}</p>)}</article>)}</div><section className="tradeoff-grid" aria-label="실제 결과 변화"><div><b>좋아진 조건</b><p>{tradeoff.improved.length ? tradeoff.improved.join(" · ") : "상태 단계가 좋아진 조건은 아직 없어요."}</p></div><div><b>그대로인 조건</b><p>{tradeoff.unchanged.length ? tradeoff.unchanged.join(" · ") : "그대로인 조건은 없어요."}</p></div><div><b>새로 살펴볼 부담</b><p>{[...tradeoff.regressed, ...tradeoff.newBurdens].join(" · ")}</p></div></section><section className="report-sentence"><h2>수송 설계 비교서</h2><p>첫 설계에서 지키려 한 조건은 <b>{redesignBaseEvaluation.conditionResults.find((item) => item.conditionId === strength)?.label}</b>이고, 재설계에서 살펴본 조건은 <b>{redesignBaseEvaluation.conditionResults.find((item) => item.conditionId === target)?.label}</b>입니다. <b>{changedComponent.name}</b>로 바꾼 뒤 실제로 좋아진 조건은 <b>{tradeoff.improved.length ? tradeoff.improved.join(" · ") : "아직 없음"}</b>이며, 대신 <b>{[...tradeoff.regressed, ...tradeoff.newBurdens].join(" · ")}</b>을 더 생각해야 합니다.</p><p className="safety">이 비교서는 실제 성능이나 안전을 보증하지 않는 교육용 결과입니다.</p></section><button className="primary" onClick={() => { setReports((old) => [...old, mission.title]); setPhase("report"); }}>비교서 완성</button></section> : null}
      {phase === "report" ? <section className="panel report"><h1>수송 설계 비교서를 완성했어요</h1><p>이번 임무에서 조건을 읽고, 네 부품을 조합하고, 한 부품만 바꾸어 절충을 비교했습니다.</p><ul>{reports.map((item, index) => <li key={`${item}-${index}`}>{item} 비교서</li>)}</ul><button className="primary" onClick={() => setPhase("missions")}>다른 임무 설계하기</button><button onClick={() => setPhase("welcome")}>처음으로</button></section> : null}
    </div><HelpDialog open={Boolean(dialog)} onClose={() => setDialog(null)} type={dialog ?? "updates"} /></main>;
}
